image: alpine:latest

pages:
  stage: deploy
  script:
    - mkdir public
    - mv index.html public/index.html
    - mv app.js public/app.js
    - mv style.css public/style.css
  artifacts:
    paths:
      - public
  only:
    - master
