image: alpine:latest

pages:
  stage: deploy
  script:
    - mkdir public
    - cd public
    - mv ../index.html index.html
    - mv ../app.js app.js
    - mv ../style.css style.css
    - mv ../img/ public/img/
  artifacts:
    paths:
      - public
  only:
    - master
